version: "3"
services:
  api:
    image: chessuz/udemy_nodeangular
    ports:
      - "5000:3050"
    links:
      - link-db
  link-db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - mongoteste:/data/db/
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/db_portal --quiet
      interval: 5s
      timeout: 5s
      retries: 12      
volumes:
  mongoteste: